# report.py
# Place this in:  tumor_detection/report.py

def generate_report(label, confidence):

    if label == 'Tumor Detected':
        report = f"""
MEDICAL ANALYSIS REPORT
========================
Result        : {label}
Confidence    : {confidence}%

FINDINGS:
The AI model has detected abnormal tissue patterns in the uploaded scan
with a confidence of {confidence}%. The highlighted region in the heatmap
indicates the area of concern.

PRECAUTIONS:
- Do not panic. AI detection is a screening tool, not a final diagnosis.
- Consult a certified neurologist or oncologist immediately.
- Bring this report and your original scan to your appointment.
- Avoid self-medication or online treatments.
- Get an MRI with contrast dye for detailed confirmation.
- Maintain a stress-free environment and proper rest.

RECOMMENDED NEXT STEPS:
1. Visit a neurologist within the next 7 days.
2. Request a contrast-enhanced MRI scan.
3. Ask your doctor about a biopsy if recommended.
4. Keep a record of any symptoms (headaches, vision changes, etc.)

DISCLAIMER:
This report is generated by an AI system for screening purposes only.
It is NOT a substitute for professional medical advice or diagnosis.
"""

    else:
        report = f"""
MEDICAL ANALYSIS REPORT
========================
Result        : {label}
Confidence    : {confidence}%

FINDINGS:
The AI model found no significant abnormal tissue patterns in the uploaded
scan with a confidence of {confidence}%.

PRECAUTIONS:
- Continue regular health check-ups as advised by your doctor.
- If you experience persistent headaches, vision problems, or dizziness,
  consult a doctor regardless of this result.
- Maintain a healthy diet, regular sleep, and low stress levels.

DISCLAIMER:
This report is generated by an AI system for screening purposes only.
It is NOT a substitute for professional medical advice or diagnosis.
"""

    return report.strip()